### ISSUE TITLE
refactor commands into command objects

### ISSUE THREAD

**Issue by Sakimori** [Sakimori/matteo-the-prestige#33]
**high priority**

**Comment by esSteres** [comment]
I'm a bit puzzled by the `on_reaction_add()` logic. It reads like something that should be part of a command, but I'm not certain where it goes. If possible it would probably be a good idea to merge it with whatever it is a part of.

Alternatively, it could be nice to have an `on_reaction_add()` for each command separately, but I think the practicalities of that are difficult. You'd somehow need to keep track of what command sent which message, as well as any persistent state required to respond to the reaction appropriately. Perhaps a way for commands to opt-in to being remembered, and then a dict from message ID to command object plus any required state. After a reaction is processed the command can say whether it still needs to be remembered (to account for one-off reactions like with create team) or whether it can be forgotten. There would need to be a way to cap the number of remembered messages, otherwise we just keep consuming memory forever. Perhaps a maximum total or a timeout for each? This is all somewhat aspirational of course. For now we can just do the reactions individually for each command

**Comment by Sakimori** [comment]
the on_reaction_add is specifically for the setupgame command. during lineup creation, the function waits for both messages and reactions. in order to wait for one without blocking the other, i had to move the reaction_add elsewhere.

**Comment by esSteres** [comment]
Okay, I'll just leave it for now if possible. it might be possible to have setupgame spin off two threads, one for messages and one for reacts, but that should probably be a separate issue (and I'm not that familiar with python async so I'm not certain it's possible)
