### ISSUE TITLE
draft mode for building a team

### ISSUE THREAD

**Issue by Sakimori** [Sakimori/matteo-the-prestige#47]
low priority. onomancer-generated names put into a pool, some number of users build teams from said pool

**Comment by jmaliksi** [comment]
you can build a pool directly from onomancer with this endpoint https://github.com/jmaliksi/onomancer#get-names

**Comment by jmaliksi** [comment]
## Proposed commands

### Start Draft
```
m;startdraft
@person1
Team Name1
This is our slogan!
@person2
Team Name2
This is another slogan!
...
```

Starts a draft with n people in the order that they can draft. Replies with text box echoing the above information and waits for n thumbs up before proceeding. After receiving all thumbs, Matteo will loop through the list and ping each person that it is their turn to draft. Matteo should throw an error if one of those @ tags is not accessible from the channel they are called in.

### Draft Player
`m;draft Player Name`

Matteo will ping each participant in order with the list of available players\* for drafting\*\*, and they and only they can reply with `m;draft`\*\*\*. Matteo will check this against who the active picker is\*\*\*\*. Anyone else typing this command and not an active picker will be ignored. After successfully picking a player to draft, Matteo will echo the participant's current roster with the new player appended.

Draft order goes 12 hitters then 1 pitcher. `13 * (n+1)` names will be drafted so that no one is "stuck" with the final pitcher. Unless we want someone to be stuck with the last person, but the pitcher is a bit too important for that. Participants should only get like 30-60 seconds to make a pick.

\*Should stars be shown? Feels like if they are, then people will err on the side of power gaming.

\*\*This list will be `13 * (n + 1)` where n is the number of participants, so it will be prohibitively large if there are a more than two participants. One possible way around this is to only show 10 or so available names at a time but that will obfuscate any juicy bottom rung picks—though this can be seen as a positive depending on perspective. Another way is to not echo the full list between picks but to have a `m;showdraft <id>` command, but I'm hesitant on this option as it a) is clunky to deal with draft IDs and b) scanning through 30-50 names is just too much cognitive load.

\*\*\*\*If someone is in two drafts at the same time and is picking at the same time, that's on them and this edge case will not be addressed in v1.

\*\*\*Note this needs to account for non-breaking spaces served by Onomancer.

## Proposed Data Models

### Team
The current team model can be leveraged, using the provided @ tag for ownership details. At draft start, these will be initialized with no one on the team\*. I don't have a strong opinion about keeping the model in memory or saving to DB after every pick. Latency on saving is probably negligible, and it'll allow for pausing/resuming drafts ie during a deploy, but also it adds complexity for a tiny edge case.

\*Unsure if that's possible out of the box or if that will require a substantial refactor. If a substantial refactor, then teams might have to be built in memory then saved to the proper object after the pitcher is chosen.

### Draft

|Field name|type|description|
|-----------|----|-----------|
|`name`|string|a draftable player's name. not unique, just in case there are multiple drafts where the same name got pulled twice.|
|`stats`|json string|full json blob of stats from onomancer|
|`draft_id`|unique string|a unique ID that represents a draft that this player is available for|

This is a simple model that can held in memory or in a new table. The intent is for each draft pick, the appropriate player's row gets deleted, though, so since the data is meant to be ephemeral, probably easiest to just handle in memory as a dictionary of dictionaries:

```
{
    draft_id: {
        player_name: {
            thwack:
            ...
        },
        ...
    },
    ...
}
```

Even with 20 people in a draft, that's only 260 entries and even with the json blob, should fit just fine in memory.

## Proposed Data/UX flow

### Draft start
1. Matteo receives command to start a draft
2. Matteo creates empty team for each participant
3. Matteo creates a draft ID by taking some digits from a UUID
4. Matteo fetches `(n+1)*13` names from [Onomancer](https://github.com/jmaliksi/onomancer#get-names) with stats and saves to draft store
5. Matteo sets draft mutex to the first participant's handle
6. Matteo displays n names from the top of the draft list for participant to draft
7. Participant types `m;draft`. Matteo checks participant against mutex and drafted player's name against top n. If invalid, throw error and repeat step 6
8. DELETE drafted player row from store, add to participant's team
9. Move draft mutex to next participant, repeat from step 6 until `num_participants <= num_draftable_players / 2` indicating final round
10. Prompt participant to draft a pitcher.
11. On valid selection, display full team.
12. Repeat from 10 until all participants have a pitcher.

**Comment by Sakimori** [comment]
i love this.

stars will not be shown
draft pools of 20 names at a time, and completely refresh the pool after 16 are chosen. gets around the prohibitively large list.

will keep everything in memory until end of draft

**Comment by jmaliksi** [comment]
makes sense!

**Comment by esSteres** [comment]
one note, should probably change pitcher draft step to be a second round where you're drafting a rotation (since there's no way this comes out before pitching rotations do)

**Comment by jmaliksi** [comment]
> one note, should probably change pitcher draft step to be a second round where you're drafting a rotation (since there's no way this comes out before pitching rotations do)
> edit: unless we specifically want only one pitcher?

my gut says that draft mode will be more often used for one-offs, but happy to revisit. I don't think switching from one draft to two drafts will be a huge leap, but one draft is probably an easier state machine (maybe)
